package com.enjoylearning.cache.mapper;

import com.enjoylearning.cache.entity.PorfitDetail;
import com.enjoylearning.cache.entity.PorfitDetailKey;
import org.apache.ibatis.annotations.*;

import java.math.BigDecimal;


public interface PorfitDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profitdetail
     *
     * @mbggenerated
     */
    @Delete({
        "delete from profitdetail",
        "where code = #{code,jdbcType=CHAR}",
          "and pcode = #{pcode,jdbcType=CHAR}",
          "and price = #{price,jdbcType=DECIMAL}",
          "and usercode = #{usercode,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(PorfitDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profitdetail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into profitdetail (code, pcode, price, ",
        "usercode, creattime)",
        "values (#{code,jdbcType=CHAR}, #{pcode,jdbcType=CHAR}, #{price,jdbcType=DECIMAL}, ",
        "#{usercode,jdbcType=CHAR}, #{creattime,jdbcType=TIMESTAMP})"
    })
    int insert(PorfitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profitdetail
     *
     * @mbggenerated
     */
    int insertSelective(PorfitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profitdetail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "code, pcode, price, usercode, creattime",
        "from profitdetail",
        "where code = #{code,jdbcType=CHAR}",
          "and pcode = #{pcode,jdbcType=CHAR}",
          "and price = #{price,jdbcType=DECIMAL}",
          "and usercode = #{usercode,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    PorfitDetail selectByPrimaryKey(PorfitDetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profitdetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PorfitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profitdetail
     *
     * @mbggenerated
     */
    @Update({
        "update profitdetail",
        "set creattime = #{creattime,jdbcType=TIMESTAMP}",
        "where code = #{code,jdbcType=CHAR}",
          "and pcode = #{pcode,jdbcType=CHAR}",
          "and price = #{price,jdbcType=DECIMAL}",
          "and usercode = #{usercode,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(PorfitDetail record);


    BigDecimal getProfitAmount(String usercode);
}